### ISSUE TITLE
Space for long tick labels

### ISSUE THREAD

**Issue by ekleins** [Bart6114/dimple#2]
Hi, 

I have an horizontal barchart with quite long tick labels (>20 characters). It is possible to adjust the space allowed for the tick labels so it can show them in its full length? See the example at
http://diodon.cbm.usb.ve/~eklein/kk/resumenes3_dimple.html

Saludos, EKS

**Comment by bart6114** [comment]
Hi @ekleins,

The `boundsX` parameter should be able to fix this for you. Have look at the example below.

```
library(dimple)
library(dplyr)

sales2 <-
  sales %>%
  mutate(Owner = ifelse(Owner == "Rekall", "Rekall - with a very long label", as.character(Owner)))


dimple(sales2,
       xCategory=c("Channel", "Price.Tier"),
       yCategory="Owner",
       series="Price.Tier",
       legend=TRUE,
       boundsX = 200)
```
